# 米游社国际服代理Host
proxyHost: ""
# 米游社国际服代理Port
proxyPort: 0
# 数据库选择（推荐sqlite）
dialect: sqlite
# postgresql配置
postgres:
  host: localhost
  port: 5432
  database: mys_core
  username: postgres
  password: a123456
